services:
    forumhulp.announcement.listener:
        class: forumhulp\announcement\event\listener
        arguments:
            - @config
            - @config_text
            - @controller.helper
            - @request
            - @template
            - @user
            - @dispatcher
        tags:
            - { name: event.listener }

    forumhulp.announcement.controller:
        class: forumhulp\announcement\controller\controller
        arguments:
            - @config_text
            - @dbal.conn
            - @controller.helper
            - @request
            - @user
